[package]
name        = "shellkit"
version     = "0.0.0"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
edition     = "2018"
description = "ğŸš Build your own shell"
license     = "CC0-1.0"
homepage    = "https://github.com/casey/shellkit"

[dependencies]
